In [1]:
import numpy as np

In [2]:
a = [2, 5, 7]

In [3]:
b = [3, 12, 27]

In [4]:
a+b

[2, 5, 7, 3, 12, 27]

In [5]:
c = [m+n for m, n in zip(a,b)]

In [6]:
c

[5, 17, 34]

In [7]:
sum(a)

14

In [8]:
np_a = np.array(a)

In [9]:
np_b = np.array(b)

In [10]:
np_a + np_b

array([ 5, 17, 34])

In [11]:
p = np.array([1,2,"abc"])

In [12]:
p

array(['1', '2', 'abc'], dtype='<U21')

In [13]:
p+ np_a

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U21'), dtype('int64')) -> None

In [14]:
np_a.max()

7

In [15]:
np_a.mean()

4.666666666666667

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np_a*np.ones(3)

array([2., 5., 7.])

In [19]:
np_a*[3]

array([ 6, 15, 21])

In [20]:
np_a*np.array([2.2])

array([ 4.4, 11. , 15.4])

In [21]:
np_a*np.array([2.2,3.2])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [22]:
np_a[1]

5

In [23]:
np_a[1:]

array([5, 7])

In [24]:
np_a[0:2]

array([2, 5])

In [25]:
np_2d = np.array([[1,2],[3,4]])

In [26]:
np_2d

array([[1, 2],
       [3, 4]])

In [27]:
np_2d.sum()

10

In [28]:
np_2d.sum(axis=0)

array([4, 6])

In [29]:
#Sum of rows
np_2d.sum(axis=1)

array([3, 7])

In [30]:
np_2d.T()

TypeError: 'numpy.ndarray' object is not callable

In [31]:
# Transpose
np_2d.T

array([[1, 3],
       [2, 4]])

In [32]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [33]:
# Identity matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np_2d

array([[1, 2],
       [3, 4]])

In [38]:
np_2d+np.ones([2,2])

array([[2., 3.],
       [4., 5.]])

In [39]:
# Numpy does broadcasting. It will match (np.ones(2)) to the elements in np_2d to do the addition
np_2d+np.ones(2)

array([[2., 3.],
       [4., 5.]])

In [40]:
np_3d = np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7]])

In [41]:
np_3d

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [42]:
np_3d + np.ones(2)

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [43]:
np_2d+np.ones(2)

array([[2., 3.],
       [4., 5.]])

In [44]:
np_2d+np.ones([2,1])

array([[2., 3.],
       [4., 5.]])

In [45]:
# Dot Product
np_dotp = np_2d.dot(np.array([[1,10,100],[1000,100,10]]))

In [46]:
np_dotp

array([[2001,  210,  120],
       [4003,  430,  340]])

In [47]:
np_dotp[0,1]

210

In [48]:
np_dotp[1:3]

array([[4003,  430,  340]])

In [49]:
np_dotp[0:2,0]

array([2001, 4003])

In [50]:
np_rs = np.array([1,2,3,4,5,6])

In [51]:
np_rs

array([1, 2, 3, 4, 5, 6])

In [52]:
np_rs.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
np_rs.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
#Use -1 to tell Numpy to figure out the number of columns
np_rs.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
np_rs.reshape(4,-1)

ValueError: cannot reshape array of size 6 into shape (4,newaxis)

In [56]:
np_rs.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
np_rs.reshape(2,2,-1)

ValueError: cannot reshape array of size 6 into shape (2,2,newaxis)

In [58]:
# Also use -1 to tell Numpy to figure out the number of rows
np_rs.reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
np.random(2)

TypeError: 'module' object is not callable

In [61]:
np.random.random(2)

array([0.22966906, 0.56417109])

In [62]:
import np.random as random

ModuleNotFoundError: No module named 'np'

In [63]:
import numpy.random as random

In [64]:
random(2)

TypeError: 'module' object is not callable

In [65]:
random.random(2)

array([0.97274837, 0.06432462])

In [65]:
random.random([3,2])

array([[0.30526688, 0.41513002],
       [0.598052  , 0.11485611],
       [0.0684223 , 0.54712717]])

In [66]:
# Linear Algebra

import numpy.linalg as la

In [67]:
la.inv(np_2d)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [68]:
la.eig(np_2d)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [69]:
# Singular value decomposition
la.svd(np_2d)

SVDResult(U=array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]]), S=array([5.4649857 , 0.36596619]), Vh=array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]]))

In [70]:
# Pseudo inverse
la.pinv(np_2d)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [71]:
# Random nos from a uniform distribution
random.rand(2,3)*5

array([[2.72887994, 3.738677  , 2.90274844],
       [4.58787261, 0.99876687, 4.0715046 ]])

In [74]:
# Random nos from a normal distribution
random.randn(2,3)

array([[-1.23473641,  1.20362352, -0.0691662 ],
       [ 0.0334294 ,  1.00109125, -0.22592634]])

In [72]:
random.randint(-2,3,5)

array([-1,  0,  0,  2,  0])

In [73]:
np_rs

array([1, 2, 3, 4, 5, 6])

In [74]:
# Suffle is useful when you don't have a lot of data
random.shuffle(np_rs)

In [75]:
np_rs

array([2, 5, 1, 4, 6, 3])

In [76]:
random.choice(np_rs, 2)

array([6, 1])

In [77]:
random.binomial(20,0.3)

9

In [78]:
random.binomial(20, 0.3, 7)

array([ 5, 10, 14,  7,  5,  8,  9])

In [80]:
random.exponential(0.7,4)

array([0.00880297, 0.08071795, 0.46414849, 0.566233  ])

In [81]:
%%time


UsageError: %%time is a cell magic, but the cell body is empty. Did you mean the line magic %time (single %)?


In [82]:
random.normal(-5,12,3)

array([-31.21602878,  17.49078197,  -1.64173464])

In [83]:
random.logistic(-2,4,7)

array([-7.8640151 , -4.76603906,  4.96656567,  5.16159321, -5.99151145,
        2.0067111 , -4.31895779])

In [84]:
np_2d.shape

(2, 2)

In [85]:
np_2d.dtype

dtype('int64')

In [86]:
type(np_2d)

numpy.ndarray

In [87]:
np.vstack(np.ones([2,2]))

array([[1., 1.],
       [1., 1.]])

In [88]:
# Stack is like concatenate
np.vstack((np_2d,np.ones([2,2])))

array([[1., 2.],
       [3., 4.],
       [1., 1.],
       [1., 1.]])

In [89]:
np.hstack((np_2d,np.ones([2,2])))

array([[1., 2., 1., 1.],
       [3., 4., 1., 1.]])

In [90]:
N=10000000
x=list(range(N))
y=list(range(N)) 
z=[]

In [91]:
np_x = np.array(x)
np_y = np.array(y)

In [92]:
%%time
for i in range(len(x)):
    z.append(x[i]+y[i])


CPU times: user 486 ms, sys: 28.9 ms, total: 515 ms
Wall time: 518 ms


In [93]:
%%time
np_z = np_x+np_y

CPU times: user 11.5 ms, sys: 45.4 ms, total: 56.9 ms
Wall time: 90.8 ms
