In [1]:
import numpy as np

In [2]:
a = [2, 5, 7]

In [3]:
b = [3, 12, 27]

In [4]:
a+b

[2, 5, 7, 3, 12, 27]

In [5]:
c = [m+n for m, n in zip(a,b)]

In [6]:
c

[5, 17, 34]

In [7]:
sum(a)

14

In [8]:
np_a = np.array(a)

In [9]:
np_b = np.array(b)

In [10]:
np_a + np_b

array([ 5, 17, 34])

In [11]:
p = np.array([1,2,"abc"])

In [12]:
p

array(['1', '2', 'abc'], dtype='<U21')

In [17]:
p+ np_a

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U21'), dtype('int64')) -> None

In [18]:
np_a.max()

7

In [19]:
np_a.mean()

4.666666666666667

In [20]:
np.ones(3)

array([1., 1., 1.])

In [21]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np_a*np.ones(3)

array([2., 5., 7.])

In [23]:
np_a*[3]

array([ 6, 15, 21])

In [24]:
np_a*np.array([2.2])

array([ 4.4, 11. , 15.4])

In [25]:
np_a*np.array([2.2,3.2])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [26]:
np_a[1]

5

In [27]:
np_a[1:]

array([5, 7])

In [28]:
np_a[0:2]

array([2, 5])

In [29]:
np_2d = np.array([[1,2],[3,4]])

In [30]:
np_2d

array([[1, 2],
       [3, 4]])

In [31]:
np_2d.sum()

10

In [32]:
np_2d.sum(axis=0)

array([4, 6])

In [33]:
#Sum of rows
np_2d.sum(axis=1)

array([3, 7])

In [34]:
np_2d.T()

TypeError: 'numpy.ndarray' object is not callable

In [35]:
# Transpose
np_2d.T

array([[1, 3],
       [2, 4]])

In [36]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [37]:
# Identity matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np_2d

array([[1, 2],
       [3, 4]])

In [40]:
np_2d+np.ones([2,2])

array([[2., 3.],
       [4., 5.]])

In [41]:
# Numpy does broadcasting. It will match (np.ones(2)) to the elements in np_2d to do the addition
np_2d+np.ones(2)

array([[2., 3.],
       [4., 5.]])

In [42]:
np_3d = np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7]])

In [43]:
np_3d

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [44]:
np_3d + np.ones(2)

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [45]:
np_2d+np.ones(2)

array([[2., 3.],
       [4., 5.]])

In [46]:
np_2d+np.ones([2,1])

array([[2., 3.],
       [4., 5.]])

In [47]:
# Dot Product
np_dotp = np_2d.dot(np.array([[1,10,100],[1000,100,10]]))

In [48]:
np_dotp

array([[2001,  210,  120],
       [4003,  430,  340]])

In [49]:
np_dotp[0,1]

210

In [50]:
np_dotp[1:3]

array([[4003,  430,  340]])

In [51]:
np_dotp[0:2,0]

array([2001, 4003])

In [52]:
np_rs = np.array([1,2,3,4,5,6])

In [53]:
np_rs

array([1, 2, 3, 4, 5, 6])

In [54]:
np_rs.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
np_rs.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [56]:
#Use -1 to tell Numpy to figure out the number of columns
np_rs.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
np_rs.reshape(4,-1)

ValueError: cannot reshape array of size 6 into shape (4,newaxis)

In [58]:
np_rs.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
np_rs.reshape(2,2,-1)

ValueError: cannot reshape array of size 6 into shape (2,2,newaxis)

In [60]:
# Also use -1 to tell Numpy to figure out the number of rows
np_rs.reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
np.random(2)

TypeError: 'module' object is not callable

In [62]:
np.random.random(2)

array([0.28666165, 0.01685708])

In [63]:
import np.random as random

ModuleNotFoundError: No module named 'np'

In [64]:
import numpy.random as random

In [65]:
random(2)

TypeError: 'module' object is not callable

In [66]:
random.random(2)

array([0.96285547, 0.77145415])

In [67]:
random.random([3,2])

array([[0.19203754, 0.49856968],
       [0.31567609, 0.37811023],
       [0.84758123, 0.81043102]])

In [68]:
# Linear Algebra

import numpy.linalg as la

In [69]:
la.inv(np_2d)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [70]:
la.eig(np_2d)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [71]:
# Singular value decomposition
la.svd(np_2d)

SVDResult(U=array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]]), S=array([5.4649857 , 0.36596619]), Vh=array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]]))

In [72]:
# Pseudo inverse
la.pinv(np_2d)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [73]:
# Random nos from a uniform distribution
random.rand(2,3)*5

array([[0.20620916, 4.27756945, 1.39937412],
       [4.06931079, 0.52888366, 3.50489417]])

In [74]:
# Random nos from a normal distribution
random.randn(2,3)

array([[-0.31216725,  0.27131341, -1.30537784],
       [-0.8296033 , -0.82179064, -0.50276351]])

In [75]:
random.randint(-2,3,5)

array([ 2, -1, -2, -1,  1])

In [76]:
np_rs

array([1, 2, 3, 4, 5, 6])

In [77]:
# Suffle is useful when you don't have a lot of data
random.shuffle(np_rs)

In [78]:
np_rs

array([6, 1, 3, 5, 2, 4])

In [79]:
random.choice(np_rs, 2)

array([6, 3])

In [80]:
random.binomial(20,0.3)

6

In [81]:
random.binomial(20, 0.3, 7)

array([3, 3, 7, 5, 6, 2, 9])

In [82]:
random.exponential(0.7,4)

array([1.59258832, 0.09899363, 0.89046653, 0.08160006])

In [83]:
%%time


UsageError: %%time is a cell magic, but the cell body is empty. Did you mean the line magic %time (single %)?


In [84]:
random.normal(-5,12,3)

array([ -7.51647261,  -9.87900966, -14.47301886])

In [85]:
random.logistic(-2,4,7)

array([-5.52172223,  2.08611929, -1.06895851, 16.50085613, -8.74276297,
       -0.60089979, 11.91744544])

In [86]:
np_2d.shape

(2, 2)

In [87]:
np_2d.dtype

dtype('int64')

In [88]:
type(np_2d)

numpy.ndarray

In [89]:
np.vstack(np.ones([2,2]))

array([[1., 1.],
       [1., 1.]])

In [90]:
# Stack is like concatenate
np.vstack((np_2d,np.ones([2,2])))

array([[1., 2.],
       [3., 4.],
       [1., 1.],
       [1., 1.]])

In [91]:
np.hstack((np_2d,np.ones([2,2])))

array([[1., 2., 1., 1.],
       [3., 4., 1., 1.]])

In [92]:
N=10000000
x=list(range(N))
y=list(range(N)) 
z=[]

In [93]:
np_x = np.array(x)
np_y = np.array(y)

In [94]:
%%time
for i in range(len(x)):
    z.append(x[i]+y[i])


CPU times: user 472 ms, sys: 97.6 ms, total: 569 ms
Wall time: 644 ms


In [95]:
%%time
np_z = np_x+np_y

CPU times: user 6.44 ms, sys: 29.1 ms, total: 35.5 ms
Wall time: 51.4 ms


### Assignment

In [101]:
np_ex = pd.read_csv("NumpyExerciseData.csv")

#### 1. Newton Method
Perform this matrix computation -> ((X'X)^-1)*X'y, use only X and y values from rows 2 to 41

In [137]:
import csv

In [297]:
# Function to read the data
def readData():
    X =[]
    y = []
    with open('NumpyExerciseData.csv') as f:
        rData = csv.reader(f)
#         skip the column names
        next(rData)
#         read X and y
        for line in rData:
#             print(line)
            xline = []
            # exclude the empty cells which are from column 7
            for s in line[:7]:
#                 print(s)
                xline.append(float(s.replace(' ','')))
            X.append(xline)
#         line 6 is the y column 
            y.append(float(line[6]))
    return (X, y)

In [298]:
# Assign X and y vectors from the function
X0, y0 = readData()

In [299]:
print(f'First first 6 lines values of X0 :\n {X0[:6]} \n')
print(f'First first 6 lines values of y0 :\n {y0[:6]}')

First first 6 lines values of X0 :
 [[1.0, 5.768, 62.55, 0.0, 28.0, 2.6, 28.0], [1.0, 8.949, 66.91, 0.0, 27.0, -2.0, 46.0], [1.0, 1.024, 34.42, 0.0, 20.0, -3.4, 14.0], [1.0, 4.534, 47.93, 0.0, 10.0, 1.1, 17.0], [1.0, 8.641, 35.26, 0.0, 30.0, 3.8, 32.0], [1.0, 1.063, 42.14, 0.0, 6.0, -2.1, 8.0]] 

First first 6 lines values of y0 :
 [28.0, 46.0, 14.0, 17.0, 32.0, 8.0]


In [325]:
# Convert rows 2 - 41 to numpy arrays for vectors X and y
X = np.array(X0[1:42])
y = np.transpose(np.array(y0[1:42]))

In [326]:
y

array([46., 14., 17., 32.,  8., 30., 22., 24., 24., 43., 30., 20.,  2.,
       19., 24., 22., 23., 25., 23., 34., 19., 46., 26., 28., 28., 33.,
       28., 22., 33., 28., 20., 25., 28., 31., 33., 41., 32., 33., 36.,
       58.,  5.])

#### Compute the weight w

In [327]:
# Find X transpose
Xt = np.transpose(X)
Xt

array([[ 1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,
         1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,
         1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,
         1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,
         1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,
         1.   ],
       [ 8.949,  1.024,  4.534,  8.641,  1.063,  5.306,  4.309,  3.739,
         3.816,  8.539,  7.129,  4.249, -2.99 ,  0.356,  5.487,  5.699,
        -0.373,  3.9  ,  3.616,  9.103,  2.714,  6.885, -0.85 ,  5.511,
         5.225,  7.982,  4.361,  2.853,  2.777,  1.977,  3.784,  3.043,
         5.618,  7.374,  3.09 ,  6.178,  4.605,  1.968,  3.61 ,  9.896,
        -0.256],
       [66.91 , 34.42 , 47.93 , 35.26 , 42.14 , 39.8  , 36.14 , 44.53 ,
        60.01 , 36.9  , 35.77 , 37.17 , 42.41 , 57.67 , 35.25 , 62.15 ,
        38.38 , 40.53 , 35.91 , 59.6  , 43.54 , 35.66 , 43.94 , 58.96 ,
        45.25 , 43.71 , 52.71 

In [328]:
XtX = np.dot(Xt, X)
XtX

array([[ 4.10000000e+01,  1.74441000e+02,  1.95647000e+03,
         7.00000000e+00,  1.11000000e+03, -1.97000000e+01,
         1.11500000e+03],
       [ 1.74441000e+02,  1.08647661e+03,  8.45150227e+03,
         2.18430000e+01,  4.78312800e+03,  1.50590000e+00,
         5.67878400e+03],
       [ 1.95647000e+03,  8.45150227e+03,  9.75721283e+04,
         2.99180000e+02,  5.41605600e+04, -9.26597000e+02,
         5.43339200e+04],
       [ 7.00000000e+00,  2.18430000e+01,  2.99180000e+02,
         7.00000000e+00,  1.82000000e+02, -4.30000000e+00,
         2.28000000e+02],
       [ 1.11000000e+03,  4.78312800e+03,  5.41605600e+04,
         1.82000000e+02,  3.98380000e+04,  2.00700000e+02,
         3.30630000e+04],
       [-1.97000000e+01,  1.50590000e+00, -9.26597000e+02,
        -4.30000000e+00,  2.00700000e+02,  2.80150000e+02,
        -4.15500000e+02],
       [ 1.11500000e+03,  5.67878400e+03,  5.43339200e+04,
         2.28000000e+02,  3.30630000e+04, -4.15500000e+02,
         3.4927000

In [329]:
XtX.shape

(7, 7)

In [330]:
Xty = np.dot(Xt, y)
Xty

array([ 1115.   ,  5678.784, 54333.92 ,   228.   , 33063.   ,  -415.5  ,
       34927.   ])

In [331]:
# Computing weight w
w = np.linalg.solve(XtX, Xty)
w

array([ 5.88412456e-12, -2.48529495e-12, -1.25645091e-13, -9.26733117e-12,
       -2.90811094e-13,  1.20718133e-12,  1.00000000e+00])

#### 2. Error Computation (both Training and Test Error)
a. Generate y values from the new generated w values

b. Compute the SSR, MSR and RMSE between the generated y values and the actual values both for the data from rows 2 to 41 and the data from rows 43 to 51

In [333]:
Xtest, ytest = X0[43:52], y0[43:52]

In [334]:
# Making predictions
for data, actual in zip(Xtest, ytest):
    x = np.array([data])
    prediction = np.dot(x, w)
    
    print(f' Prediction = {prediction[0]}, Actual = {actual}')
    

 Prediction = 10.000000000000243, Actual = 10.0
 Prediction = 19.999999999999837, Actual = 20.0
 Prediction = 6.000000000000402, Actual = 6.0
 Prediction = 28.00000000000006, Actual = 28.0
 Prediction = -1.0000000000002096, Actual = -1.0
 Prediction = 25.000000000000124, Actual = 25.0
 Prediction = 34.000000000000384, Actual = 34.0


In [335]:
# Calculating the residuals
for data, actual in zip(Xtest, ytest):
    x = np.array([data])
    prediction = np.dot(x, w)
    SSR = (prediction[0] - actual)**2
    MSR = np.divide(SSR,len(x))
    RMSR = np.sqrt(MSR)
    
    print(f' Prediction = {prediction[0]}, Actual = {actual}')
    print(f' SSR = {SSR}')
    print(f' MSR = {MSR}')
    print(f' RMSR = {RMSR}\n \n')
    
    

 Prediction = 10.000000000000243, Actual = 10.0
 SSR = 5.922452132037268e-26
 MSR = 5.922452132037268e-26
 RMSR = 2.433608869978343e-13
 

 Prediction = 19.999999999999837, Actual = 20.0
 SSR = 2.6707674807162576e-26
 MSR = 2.6707674807162576e-26
 RMSR = 1.6342482922482304e-13
 

 Prediction = 6.000000000000402, Actual = 6.0
 SSR = 1.6188135749949861e-25
 MSR = 1.6188135749949861e-25
 RMSR = 4.0234482412415673e-13
 

 Prediction = 28.00000000000006, Actual = 28.0
 SSR = 3.6476928257419586e-27
 MSR = 3.6476928257419586e-27
 RMSR = 6.039613253960852e-14
 

 Prediction = -1.0000000000002096, Actual = -1.0
 SSR = 4.3936396977189474e-26
 MSR = 4.3936396977189474e-26
 RMSR = 2.0961010704922955e-13
 

 Prediction = 25.000000000000124, Actual = 25.0
 SSR = 1.546167374233183e-26
 MSR = 1.546167374233183e-26
 RMSR = 1.2434497875801753e-13
 

 Prediction = 34.000000000000384, Actual = 34.0
 SSR = 1.472203775759661e-25
 MSR = 1.472203775759661e-25
 RMSR = 3.836930773104541e-13
 



#### 3. Regularized Newton
Next step perform the matrix computation -> ((X'X+lambda*I)^-1)*X'y, using only X and y values from rows 2 to 41

Use lambda as 0.17

Compute and report both training and test errors for the regularized Newton computation

In [370]:
Xtrain = X
ytrain = y

In [371]:
def regNum(X, y, lmd):
    lmd = 0.17
    regNumerator = np.add(XtX, np.dot(lmd, np.identity(len(XtX))))
    
    regNewton = np.linalg.solve(regNumerator, Xty)
    
    return regNewton

In [372]:
Xtest = np.array(X0[43:])
ytest = np.array(y0[43:])

In [373]:
theta = regNum(Xtrain, ytrain, lmd)
print(f'FittedOr: {theta}')

FittedOr: [-2.98122946e-02  1.42742094e-02  6.67310820e-04  5.15302839e-02
  1.67157681e-03 -6.91353949e-03  9.95586935e-01]


In [369]:
# Making predictions
for data, actual in zip(Xtest, ytest):
    x = np.array([data])
    prediction = np.dot(x, theta)
    
    print(f' Prediction = {prediction[0]}, Actual = {actual}')

 Prediction = 10.000309980670682, Actual = 10.0
 Prediction = 20.001929806300424, Actual = 20.0
 Prediction = 5.998784295065942, Actual = 6.0
 Prediction = 27.998559115082934, Actual = 28.0
 Prediction = -0.9974781496753786, Actual = -1.0
 Prediction = 25.000463286315277, Actual = 25.0
 Prediction = 33.998398924136254, Actual = 34.0


In [375]:
# Calculating the residuals on the training data
for data, actual in zip(Xtrain, ytrain):
    x = np.array([data])
    prediction = np.dot(x, theta)
    SSR = (prediction[0] - actual)**2
    MSR = np.divide(SSR,len(x))
    RMSR = np.sqrt(MSR)
    
    print(f' Training data prediction = {prediction[0]}, Actual = {actual}')
    print(f' Training data SSR = {SSR}')
    print(f' Training data MSR = {MSR}')
    print(f' Training data RMSR = {RMSR}\n \n')
    

 Training data prediction = 45.99853602310581, Actual = 46.0
 Training data SSR = 2.1432283467318854e-06
 Training data MSR = 2.1432283467318854e-06
 Training data RMSR = 0.0014639768941933085
 

 Training data prediction = 14.002927991049772, Actual = 14.0
 Training data SSR = 8.573131587543214e-06
 Training data MSR = 8.573131587543214e-06
 Training data RMSR = 0.0029279910497717054
 

 Training data prediction = 17.000979943588888, Actual = 17.0
 Training data SSR = 9.602894374026486e-07
 Training data MSR = 9.602894374026486e-07
 Training data RMSR = 0.000979943588887977
 

 Training data prediction = 31.999718294099566, Actual = 32.0
 Training data SSR = 7.93582143395018e-08
 Training data MSR = 7.93582143395018e-08
 Training data RMSR = 0.00028170590043430366
 

 Training data prediction = 8.002725039634475, Actual = 8.0
 Training data SSR = 7.425841009460316e-06
 Training data MSR = 7.425841009460316e-06
 Training data RMSR = 0.0027250396344751238
 

 Training data prediction = 

In [376]:
# Calculating the residuals on the test data
for data, actual in zip(Xtest, ytest):
    x = np.array([data])
    prediction = np.dot(x, theta)
    SSR = (prediction[0] - actual)**2
    MSR = np.divide(SSR,len(x))
    RMSR = np.sqrt(MSR)
    
    print(f' Test data prediction = {prediction[0]}, Actual = {actual}')
    print(f' Test data SSR = {SSR}')
    print(f' Test data MSR = {MSR}')
    print(f' Test data RMSR = {RMSR}\n \n')
    

 Test data prediction = 10.000309980670682, Actual = 10.0
 Test data SSR = 9.608801619652976e-08
 Test data MSR = 9.608801619652976e-08
 Test data RMSR = 0.00030998067068210844
 

 Test data prediction = 20.001929806300424, Actual = 20.0
 Test data SSR = 3.724152357157227e-06
 Test data MSR = 3.724152357157227e-06
 Test data RMSR = 0.001929806300424275
 

 Test data prediction = 5.998784295065942, Actual = 6.0
 Test data SSR = 1.4779384866929218e-06
 Test data MSR = 1.4779384866929218e-06
 Test data RMSR = 0.0012157049340579817
 

 Test data prediction = 27.998559115082934, Actual = 28.0
 Test data SSR = 2.076149344229442e-06
 Test data MSR = 2.076149344229442e-06
 Test data RMSR = 0.0014408849170663984
 

 Test data prediction = -0.9974781496753786, Actual = -1.0
 Test data SSR = 6.359729059792947e-06
 Test data MSR = 6.359729059792947e-06
 Test data RMSR = 0.0025218503246213775
 

 Test data prediction = 25.000463286315277, Actual = 25.0
 Test data SSR = 2.1463420992307412e-07
 Test 

#### 4. Compute R-squared values for both Newton and Regularized Newton on both train and test datasets
Look up how to compute R-squared values in excel

In [ ]:
# Calculating R2 on Newton training data
for data, actual in zip(Xtrain, ytrain):
    x = np.array([data])
    prediction = np.dot(x, w)
    SSR = (prediction[0] - actual)**2
    MSR = np.divide(SSR,len(x))
    RMSR = np.sqrt(MSR)
    
    print(f' Test data prediction = {prediction[0]}, Actual = {actual}')
    print(f' Test data SSR = {SSR}')
    print(f' Test data MSR = {MSR}')
    print(f' Test data RMSR = {RMSR}\n \n')
    